import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  button_footer_container: {
    width: "50%",
    marginTop: 5,
    paddingHorizontal: 5,
  },
  button_footer: {
    height: 50,
    borderRadius: 10,
  },
  buttons_footer: {
    flexDirection: "row",
    justifyContent: "space-between",
    margin: 10,
  },
  aceptado: {
    backgroundColor: "#c9f7c9",
    paddingHorizontal: 10,
  },
  rechazado: {
    backgroundColor: "#f7c9c9",
    paddingHorizontal: 10,
  },
  pendiente: {
    backgroundColor: "#f7f7c9",
    paddingHorizontal: 10,
  },
  compartimientos: {
    flexDirection: "row",
    gap: 10,
    marginVertical: 10,
    paddingHorizontal: 20,
    marginBottom: -5,
  },
  compartimiento_selected: {
    backgroundColor: "#c90000",
    borderColor: "#c90000",
    color: "#ffffff",
  },
  compartimiento: {
    borderRadius: 10,
    borderColor: "black",
    borderWidth: 1,
    paddingHorizontal: 15,
    paddingVertical: 5,
    backgroundColor: "#ffffff",
  },
  is_modal: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modal_text: { fontSize: 16 },
  modal_view: {
    margin: 20,
    backgroundColor: "white",
    borderRadius: 20,
    paddingHorizontal: 40,
    paddingVertical: 30,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    flexDirection: "column",
    gap: 20,
  },
  input: { textAlign: "right", fontSize: 14, fontWeight: "bold" },
  form: {
    height: "100px",
  },
  optionText: { textTransform: "capitalize", fontSize: 12 },
  optionTextSelect: { color: "white" },
  radio_main: {
    flexDirection: "row",
    width: "50%",
    alignItems: "center",
    padding: 0,
    gap: 10,
  },
  optionButton: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 5,
    padding: 8,
    flex: 1,
  },
  selectedOption: {
    backgroundColor: "#c90000",
    borderColor: "#c90000",
  },
  input_area: { fontSize: 14, fontWeight: "bold" },
  field_input_area: {
    height: 100,
    width: "50%",
    padding: 8,
    borderStyle: "solid",
    borderWidth: 0.2,
    borderColor: "#000",
    borderRadius: 5,
    display: "flex",
    alignItems: "left",
  },
  field_input: {
    height: 34,
    width: "50%",
    display: "flex",
    justifyContent: "center",
    alignItems: "left",
    padding: 8,
    borderStyle: "solid",
    borderWidth: 0.2,
    borderColor: "#000",
    borderRadius: 5,
  },
  field_icon: {
    gap: 10,
  },
  field: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  field_info: {
    textTransform: "capitalize",
  },
  container: {
    paddingHorizontal: 5,
    paddingVertical: 5,
    flex: 1,
  },
  card_view: { flex: 1 },
  info_main: {
    alignItems: "center",
    marginBottom: 5,
    width: "100%",
    flex: 1,
  },
  info_navigation: {
    flexDirection: "row",
    alignItems: "center",
  },
  info: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },

  date: { textTransform: "capitalize" },
  info_ruta: { textTransform: "capitalize", color: "#c90000" },
  litros: { color: "#c90000", fontWeight: "bold", fontSize: 20 },
});
